// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model1.Repositories;

namespace Model1.Migrations
{
    [DbContext(typeof(EFBankContext))]
    [Migration("20201117145852_Initial Seeding")]
    partial class InitialSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model1.Entities.Klant", b =>
                {
                    b.Property<int>("KlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlantId");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            KlantId = 1,
                            Naam = "Marge"
                        },
                        new
                        {
                            KlantId = 2,
                            Naam = "Homer"
                        },
                        new
                        {
                            KlantId = 3,
                            Naam = "Lisa"
                        },
                        new
                        {
                            KlantId = 4,
                            Naam = "Maggie"
                        },
                        new
                        {
                            KlantId = 5,
                            Naam = "Bart"
                        });
                });

            modelBuilder.Entity("Model1.Entities.Rekening", b =>
                {
                    b.Property<int>("RekeningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<string>("RekeningNr")
                        .HasColumnType("nvarchar(19)")
                        .HasMaxLength(19);

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("RekeningId");

                    b.HasIndex("KlantId");

                    b.HasIndex("RekeningNr")
                        .IsUnique()
                        .HasFilter("[RekeningNr] IS NOT NULL");

                    b.ToTable("Rekeningen");

                    b.HasData(
                        new
                        {
                            RekeningId = 1,
                            KlantId = 1,
                            RekeningNr = "BE68 1234 5678 9012",
                            Saldo = 1000m,
                            Soort = "Z"
                        },
                        new
                        {
                            RekeningId = 2,
                            KlantId = 1,
                            RekeningNr = "BE68 2345 6789 0169",
                            Saldo = 2000m,
                            Soort = "S"
                        },
                        new
                        {
                            RekeningId = 3,
                            KlantId = 2,
                            RekeningNr = "BE68 3456 7890 1212",
                            Saldo = 500m,
                            Soort = "S"
                        });
                });

            modelBuilder.Entity("Model1.Entities.Rekening", b =>
                {
                    b.HasOne("Model1.Entities.Klant", "Klant")
                        .WithMany("Rekeningen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
